"""Turn the declarations into chart values.

This script is what keeps §8 true in a cluster. "Add a function is one PR and
zero infra tickets" survives only if the Deployment is derived from
`function.yaml` -- the moment somebody hand-writes one, the eleventh function
needs an infra ticket and the claim is gone.

So nothing in the chart is per-function. This reads every declaration and
writes the values the chart renders from.

    python scripts/generate_values.py --check    # CI: fail if it is stale
    python scripts/generate_values.py            # rewrite it

`--check` matters more than it looks. Generated files that are committed drift
the moment somebody edits a declaration and does not regenerate, and the failure
is silent -- the cluster keeps running the old timeout. CI running `--check` is
what makes the generated file trustworthy.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHART = ROOT / "deploy" / "chart"
GENERATED = CHART / "values-functions.yaml"

HEADER = """\
# GENERATED by scripts/generate_values.py -- do not edit.
#
# Every value below comes from a declaration in functions/ or hydrator.yaml,
# because §8 makes those the single source of truth for what a function is.
# Editing this file directly puts the cluster and git out of step in a way
# nothing will report; edit the declaration and regenerate.
#
# CI runs `generate_values.py --check`, which fails when this is stale.
"""


def _name(function_id: str) -> str:
    """Kubernetes names are DNS labels: lowercase, hyphens, no underscores."""
    return function_id.replace("_", "-")


def collect() -> list[dict]:
    import yaml

    functions = []
    paths = sorted((ROOT / "functions").glob("*/function.yaml"))
    hydrator = ROOT / "hydrator.yaml"
    if hydrator.exists():
        # First: it is upstream of everything and reads best at the top.
        paths = [hydrator, *paths]

    for path in paths:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        resources = data.get("resources") or {}

        entry = {
            "id": data["function_id"],
            "name": _name(data["function_id"]),
            "version": str(data["function_version"]),
            "image": data["image"],
            "inFlight": data.get("in_flight", 1),
            "perFileTimeoutSeconds": data.get("per_file_timeout_seconds", 300),
            "retryBudget": data.get("retry_budget", 3),
            "rebalanceDrainSeconds": data.get("rebalance_drain_seconds", 30),
            "dlqTopic": data.get("dlq_topic", f"faas.dlq.{data['function_id']}"),
            "resultsTopicPartitions": data.get("results_topic_partitions", 200),
            "resources": {
                "cpu": resources.get("cpu", 1),
                "memory": resources.get("memory", "512Mi"),
            },
        }
        if resources.get("gpu"):
            entry["resources"]["gpu"] = resources["gpu"]
        if data.get("input_topic"):
            entry["inputTopic"] = data["input_topic"]
        if data.get("results_topic"):
            entry["resultsTopic"] = data["results_topic"]

        functions.append(entry)

    return functions


def render(functions: list[dict]) -> str:
    import yaml

    return HEADER + yaml.safe_dump(
        {"functions": functions}, sort_keys=False, default_flow_style=False, width=100
    )


def topic_plan(functions: list[dict]) -> list[dict]:
    """The topics the declarations imply.

    Partition counts come from the declarations rather than a constant: the SDK
    computes each result's partition itself and passes it explicitly, so a topic
    smaller than `results_topic_partitions` fails when the first result is
    produced. Deriving it here means the two cannot disagree.
    """
    results_partitions = max(f["resultsTopicPartitions"] for f in functions)
    internal = next(
        (f["resultsTopic"] for f in functions if f["id"] == "hydrator" and f.get("resultsTopic")),
        "faas.audio.internal",
    )

    topics = [
        {"name": "faas.calls.raw", "partitions": 12},
        {"name": internal, "partitions": results_partitions},
        {"name": "faas.results", "partitions": results_partitions},
    ]
    topics += [{"name": f["dlqTopic"], "partitions": 3} for f in functions]
    return topics


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the generated file is stale, without writing",
    )
    args = parser.parse_args(argv)

    functions = collect()
    rendered = render(functions)

    if args.check:
        current = GENERATED.read_text(encoding="utf-8") if GENERATED.exists() else ""
        if current != rendered:
            print(
                f"{GENERATED.relative_to(ROOT)} is out of date with the declarations.\n"
                f"Run: python scripts/generate_values.py",
                file=sys.stderr,
            )
            return 1
        print(f"{GENERATED.name} matches {len(functions)} declarations")
        return 0

    GENERATED.parent.mkdir(parents=True, exist_ok=True)
    GENERATED.write_text(rendered, encoding="utf-8")

    print(f"{len(functions)} declarations -> {GENERATED.relative_to(ROOT)}")
    for topic in topic_plan(functions):
        print(f"  topic {topic['name']:<28} {topic['partitions']:>4} partitions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
